---

# (C) Copyright 2022 Hewlett Packard Enterprise Development LP

#-----------------------------------------------------------------#
#  Jobs fulfilled:                                                #
#   1) User Creation                                              #
#                                                                 #
#-----------------------------------------------------------------#

- hosts: localhost 
  vars_files:
  - variables.yaml

  tasks:

  - name: Choosing the environment
    set_fact: 
      iam_endpoint: "{% if env_var == 'intg' %}{{iam_endpoint_intg}}{% else %}{{iam_endpoint_prod}}{% endif %}"
      dfaas_endpoint: "{% if env_var == 'intg' %}{{dfaas_endpoint_intg}}{% else %}{{dfaas_endpoint_prod}}{% endif %}"

#------------------------------------------------------------------#
#                       Login Token                                #
#------------------------------------------------------------------#

  - name: Get login token
    ansible.builtin.uri:
      url: "{{ issuer }}/v1/token"
      method: POST
      validate_certs: no
      return_content: yes
      force_basic_auth: true
      timeout: 60
      headers:
        Content-type: application/x-www-form-urlencoded
      body: 
        "client_id": "{{ api_client_id }}"
        "client_secret": "{{ api_client_secret }}"
        "grant_type": "client_credentials"
        "scope": "hpe-tenant"
      body_format: form-urlencoded
      status_code: 200
    ignore_errors: no
    register: access_data
    until: access_data.status not in glc_rest_api_default_retry_status_codes
    retries: "{{ glc_rest_api_max_retry_count }}"
    delay: "{{ glc_rest_api_max_retry_delay }}"

  - debug:
      var: access_data
    when: debug_mode is defined and debug_mode == "on"

  - set_fact:
      access_token: "{{ access_data.json.access_token }}"
    when: access_data.json.access_token != []

  - debug:
      msg: "Access_token: {{ access_token }}"
    when: debug_mode is defined and debug_mode == "on" and access_token is defined

#-------------------------------------------------------------------#
#                        User Creation                              #
#-------------------------------------------------------------------#

  - name: Create lab user in GLC [{{ user.email }}]
    uri:
      url: https://{{ dfaas_endpoint }}/invite_user
      method: POST
      validate_certs: no
      return_content: yes
      force_basic_auth: true
      timeout: 60
      headers:
        Authorization: "{{ access_token }}"
        Accept: application/scim+json
        Content-type: application/scim+json
      body: |
        {
          "mailId": "{{ user_email_Id }}",
          "countryCode": "{{ country_code }}",
          "firstName": "{{ last_name }}",
          "lastName": "{{ first_name }}",
          "tenantID": "{{ tenant_id }}"
        }
      body_format: json
      status_code: [200, 201]
    ignore_errors: no
    register: user_data
    until: user_data.status not in glc_rest_api_default_retry_status_codes
    #retries: "{{ glc_rest_api_max_retry_count }}"
    delay: "{{ glc_rest_api_max_retry_delay }}"



